name: Node.js CI + Docker CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/atividade-ci

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run unit tests (no container)
        run: npm test

      - name: Build Docker image
        run: docker build -t meu-app .

      - name: Run container for health check
        run: |
          docker run -d --name app -p 3000:3000 meu-app
          echo "Aguardando app iniciar..."
          sleep 8
          curl --fail http://localhost:3000/api/funcionarios || (docker logs app && exit 1)
          docker logs app

      - name: Stop and remove container
        if: always()
        run: |
          docker stop app || true
          docker rm app || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Docker Hub)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile 
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/atividade-ci:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/atividade-ci:${{ github.sha }}